### PR TITLE
Feature/import actor

### PR DESCRIPTION
**Pull request by pconcepcion**
This pull requests adds a new feature to be able to import an NPC or a Creature from the raw text description.

_**This has been converted from a macro code and, it's a first working version, there is quite some room for improvement, but it's basically functional now.**_

To do so it adds a new button on the _GM Tools_ menu that shows a new dialog (`CoC7ActorImporterDialog`)

##  `CoC7ActorImporterDialog`
There the user can select the type of actor (NPC or Creature), and if the system should convert the stats from 6th edition to 7th that has 3 options:
* `Guess`: it will check all the _Characteristics_ if all of them are under 30 it will do the conversion, otherwise it will not.
* `Convert`: Will always do the conversion
* `No Convert`: Will not do the converstion
The conversion consist on multiplying all the _Characteristics_ by 5 and converting the _damage bonus_ following the conversion rules.
Below the to selectors there is a big text area to paste the NPC or Creature data and bellow that the _Import_ and _Cancel_ buttons. 

When the _Import_ button is clicked takes the selected options and the actor texts and generates a new actor with the help of the `CoC7ActorImporter` class and the regular expressions on `module/apps/actor-importer.js`

## `CoC7ActorImporter`

The main aim of this class is to get the raw textual character description and generate an actor with it's values from the text. 
Most of it it's done by extracting values from the text using regular expressions. 
The main entry points for the class are: `parseCharacter(text)` and `createActor(inputs)`.

### Caveats
* The class does a **best effort** to extract the information from the text, but since it depends a lot on the input text, it will generate most probably inaccurate results, that will require a minor review.
* Occupations are not extracted
* Mistakes are more common on the spells and skills part 

### TODO
* Move the regular expressions to it's own class and refactor it to use i18n and be able to import characters on any language giving the language regular expressions.  
* Add tests
* Integrate better with the actor class. 
* Create usage documentation
* Add more code documentation

### CODE REVIEW

**Review by HavlockV — APPROVED** [review]
Thanks for your help, that's something people have been asking for for along time !

**Comment by kael79** [comment]
Thank's man !

**Comment by kael79** [comment]
Bug report : if you duplicate a import npc, you can't open npc sheet

**Comment by alexandro-sierpinski** [comment]
Hello man, how are you?
I would like to know if you have a macro for ammunition linked to weapons, in this case, using the stored ammunition when loading the weapon. I'm horrible with DEV    ; -;

**Pull request merged**
