### PR TITLE
Add all occupations and missing skills…

### PR DESCRIPTION
**Pull request by marcstraube**
…from the Call of Cthulhu - 7th Ed  Investigator's Handbook.

Add german translation for skills and occupations.

## Description.

- Add all occupations from the Call of Cthulhu - 7th Ed Investigator's Handbook.
- Add missing skills (mostly languages and art/craft).
- Set sane defaults for any occupation that contains a skillset with an "any" option (Art/Craft, Fighting, Firearms).
- Add german translation for both compendia.
- Add SVG icons (all icons are from game-icons.net and svg-repo.com).

## Motivation and Context.

Make it easier for game masters and players to create new investigators (via the Investiagor Creation Wizard).

#598 

## Types of Changes.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

### CODE REVIEW

**Comment by petergeneric** [comment]
Merging this in would be a huge improvement to the system!

**Comment by petergeneric** [comment]
Thank you for your work on this, it's been a big help fo my newer players.

Can I suggest changing the Occupation "Hooker" to "Prostitute" - Prostitute is the name used in the 7e Rulebook, and in English hooker is a slang word (and I think carries a more negative connotation than prostitute)

I think it would be sensible to change the name to more inclusive & modern wording, e.g. "sex worker".
This approach could also be used for other Occupations:
- Hooker -> Sex Worker
- Conman -> Con Artist
- Stuntman -> Stunt Performer

Additionally, there are a few gendered terms that could be replaced, and which would help foster a more inclusive environment for non-binary folks:
- Outdoorsman/-woman -> Outdoor enthusiast (as Chaosium use in their prose; I've used "Outdoorsy sort" in my game but it's very informal language)
- Gentleman/Lady -> Gentry

(I've also suggested these as improvements to the books to Bridgett & Dustin at Chaosium)

**Comment by marcstraube** [comment]
I used the occupation names I got in my english version from the rules book - if there are newer names I'm open to change them. About the other more inclusive wording - I'm personally against it. Not because I'm against inclusion but because deviation from the official wording makes it more complicated for non-native speakers like me to find the thing you're looking for. I personally would never look at "Gentry" to find "Gentleman".
I would recommend for everyone that wants to make it more inclusive to copy the entry into your world or compendium and overwrite the original entry via setting a higher priority.

**Comment by petergeneric** [comment]
Yes it looks like it was revised then - my Investigator's Handbook (published September 2019) and the current PDF from Chaosium use "Prostitute" as the occupation title. That's the only difference in names I spotted between your list and the current PDF.

On changing other occupation titles, I just wanted to raise the suggestion to see what people thought - wanting to keep the wording from the Chaosium text is, I think, a reasonable approach (especially, as you pointed out, for non-native speakers).

As you say, it's easily fixed by duplicating & setting a higher priority (and, of course, keepers may well be doing this anyway so that they can write some of their own flavour text on the occupations for players who haven't yet invested in an Investigator's Handbook).

**Comment by marcstraube** [comment]
I'm going to update "Hooker" to "Prositute" later tonight. Thank you very much for your input!
Could you check if the pages are still the same in your revised version?

**Comment by snap01** [comment]
Unfortunately this pull request contains copyrighted material so can not be merged in

**Comment by marcstraube** [comment]
@snap01  If you can't merge this, please also close the open issue #598 This was the reason I made all that work and it contains exactly what was described in this issue (only occupation names and skills; no descriptions).

**Pull request closed without merging**
