### PR TITLE
Added a first version of a user's guide.

### PR DESCRIPTION
**Pull request by jantoniomartin**
I have created a basic user guide. Feel free to merge the pull request or take the text and use it for the wiki, as you wish.
I would like to improve the documentation, but it seems that the wiki cannot be contributed.

### CODE REVIEW

**Review by HavlockV — APPROVED** [review]
Thanks for your help !
Someone also started a documentation : @pconcepcion / discord : @AzHaR#1272 
I'll keep both of them. Maybe you could coordinate with him.

**Comment by pconcepcion** [comment]
@jantoniomartin I've done another pull request #430 with a very similar idea, I had also added some extra work in progress for some more documentation on my [feture/doc branch](https://github.com/pconcepcion/CoC7-FoundryVTT/tree/feature/doc). but before doing another pull request I think we can merge both options and work together, I like the idea of having a folder for each lang, but would be nice to have README.md on the root folder (either `doc` or `docs`) linking the rest of the documentation. 
What do you think?

**Comment by jantoniomartin** [comment]
@pconcepcion I totally agree, and I'm open to do it as you see fit. This is how I would do it:
- Under `doc` or `docs`, create a directory for each language and a main index.
- An index under each language directory, with links as in your first version.
- All your content under `en`.
- I would split my text in different files, linked from the index, and integrating the character creation stuff into your text.

**Comment by pconcepcion** [comment]
OK, I've moved my files to `docs/en` to match your structure, I've some work in progress files, but I'm not totally convinced of the structure, so we can change it as we think it makes more sense. 
I've put the initial idea of list of the files/sections on `README.md` but we may find a better organization. 
I like the index per language :) 
I've also merged my `feature/doc` branch into a `improve-docs`.

**Comment by pconcepcion** [comment]
@jantoniomartin I've done a bit the refactor and mixed everything under `docs`:
* Include a link to your user-guide on `doc/en/README.md`
* Add an initial version of spanish documentation on `docs/es/`
* Add a `docs/README.md` linking both Spanish and English documentation.

It's all on my [`improve-docs` branch](https://github.com/pconcepcion/CoC7-FoundryVTT/tree/improve-docs/docs)

I did try to do a Pull request to your `improve-docs` branch so you can add your changes and then do the PR to @HavlockV's one, but I did realize that my PR included a lot of other files so I cancel it, so now I'm not sure how to merge this...

One idea could be to have an `improve-docs` branch at HavlockV's repository where we can keep sending both (and anyone interested on giving an hand) PRs, and then move it from there to `develop`/`master` when there will be a release.

What do you think? (by the way I feel we could move this conversation to the issue #328)

**Comment by jantoniomartin** [comment]
@pconcepcion I don't think you need to do a PR into my fork. I made a couple of PRs from my `develop` branch to @HavlockV's `develop` branch, but I agree that having a specific branch in the upstream repo is a good idea. Maybe @HavlockV can gives us his opinion on the subject.

**Comment by HavlockV** [comment]
Hi guys. First of all thanks for your help. That's something a lots a people have been asking for.
You may also get contacted by someone that wants to publish an article on the foundryhub based on your docs.
For having a specific branch in the upstream repo, I don't really have an opinion for the simple reason that I'm not sure what this is.
I'm very new and inexperienced with github.
Just tell me what you neee and I'll accommodate. If I understood correctly you want to create a 3rd branch that will get merged in master that's very fine with me.

**Comment by pconcepcion** [comment]
Yes, @HavlockV this could be a separate branch created from `develop`  were are only merged pull-requests with changes on the documentation, and when you are going to do a new release you can merge that branch into `develop` before doing the release and incorporate the changes of the documentation for that release. 
If we do it this way we (and anyone else willing to help) can both do a PR to that branch to improve the documentation.

**Comment by pconcepcion** [comment]
@jantoniomartin I've done the PR (#450) to the new `documentation` branch with the mix and the initial Spanish docs.

**Pull request merged**
