### PR TITLE
Adding support for pulp talents on npcs/creatures.

### PR DESCRIPTION
**Pull request by kckaiwei**
I'm new to modding for Foundy, and figured this was an easy issue to learn on:

https://github.com/HavlockV/CoC7-FoundryVTT/issues/322

UAT: 

1. Create new creature/npc
2. Change system settings to pulp enabled
3. Drag/drop talent onto sheet. Alternatively create a talent when unlocked.

I need some review on whether I create the talents as an item correctly. It seems right, but when I was debugging I found that data.items on the `base.js` was changing the types of all the items to talents, and thus showing any added skills and weapons as both skill/weapons and talent. I fixed the issue by getting `itemsByType` after looking through how it was handled elsewhere, but that leads me to believe I didn't create the embeddedEntities correctly?

Debug statements did show that `data` being passed had the correct `talent` type. But once `getData()` was called in `base.js`, `data.items` ended up changing, although `data.skills` and `data.weapons` still populated correctly. I couldn't find anything out while looking at `super().getData()` from `ActorSheet`

Is there any sort of automated testing in place? I did do manual testing with drag/drop and creating talents.

What is the SOP for doing translations? Wait for a translator? or feed through Google Translate.

### CODE REVIEW

**Comment by HavlockV** [comment]
Hi kckaiwei.
First of all thanks for your participation.
A small word of warning. I'm not a developer, I started development with this project. So I may not have the correct 'phraseology'.
Had a quick look at your code.
The issue seems to be coming from the line 222 in the modified base.js :
data.talents = data.items.filter(item => item.type = "talent") (assignation)
should be changed for :
data.talents = data.items.filter(item => item.type == "talent") (comparison)
If your using itemsByType the data.talents matrix is not necessary and can be removed.
Regarding the 'SOP'( standard operating procedure ?)  there's no really anything like that; I don't even have a clue on how to do so. Then lang files used in the system are provided by users. I just publish them with the system.
Regarding the  automated testing, same thing. I don't have an idea on how to do that or proceed. I'm doing manual testing, then publishing correction when people find something on github.

**Comment by kckaiwei** [comment]
Glad to be here, and no problem with phraseology. You've done really good work here, and I'm getting into CoC7 to play, so I figured I'd contribute some to help learn the system, and for fun.

Yea, that's a good catch, definitely typo'd that and forgot, haha.

Regarding standard operating procedure, I was mostly asking since I can't do the translations, and didn't know if you categorized any new changes so translators know what new things have been added. I would suggest adding a section on how to get up and running in the readme, 

Yeah, I took a look at 5e's system module and it seems that they don't have any automated testing as well, so I guess it's just not a thing with foundryvtt :\. Not having regression tests sucks since you don't know if new changes break anything, especially as someone new jumping on the project. I don't know the features intimately, so any new changes could possibly break something.

I've made the correction and am good for you to take a review when you're ready. Regarding removing `data.talents`, I'm thinking of keeping it in for now, I suspect additional Pulp Cthulhu changes will need access/changes to `data.talents` and I found logging `data` to have been one of the quickest ways I got to understanding the code.

**Comment by HavlockV** [comment]
Help always appreciated.
I'll have a closer look ASAP and publish it with the next release.
Thanks for the contribution

**Comment by joaovscorreia** [comment]
I believe this PR was resolved in some other way by @HavlockV. I will close it for now. If there are still any changes you want to make, just say and it will be reopened!

**Pull request closed without merging**
